### ISSUE TITLE
[ERROR] ssdb_impl.cpp(57): open db failed

### ISSUE THREAD

**Issue by karlhell** [ideawu/ssdb#647]
前两天从1.8.0升级到了1.8.2，一开始没问题，过了两天ssdb无法服务，重启时出现：
[ERROR] ssdb_impl.cpp(57): open db failed
[FATAL] ssdb-server.cpp(62): could not open data db: /data/ssdb-data/data

请问这大概是什么原因？

**Comment by ideawu** [comment]
是否是权限问题?

**Comment by iamAzeem** [comment]
@ideawu: I have experienced the same thing but it was due to that another ssdb process was already running. The command `$ ps aux | grep ssdb` helped. BTW, I would suggest that there should be a proper error message like "SSDB is already running" or something like this instead of `./var/data/LOCK` in the error.

You may close this as resolved! 👍
